### ISSUE TITLE
Handle oauth and openid clients of www.prx.org on exchange.prx.org

### ISSUE THREAD

**Issue by farski** [PRX/proxy.prx.org#5]
(Moved from https://github.com/PRX/corporate.prx.org/issues/72)

There are a number of apps that use oauth or even openid against www.prx.org (exchange app), and that will need to be updated to work against exchange.prx.org.

Perhaps they would follow a redirect, but more likely they will break.

Another option would be to proxy these oauth/openid requests via www.prx.org still.

Most of them also make api requests to `www` as well, which would also need to be proxied or updated.

Off hand, I believe these would be affected:
* Fixer
* networks
* castle
* remix-select
* wfmt-services

estimate of 5 may not be enough if it is updating all those apps, or too much if perhaps can handle via proxy

**Comment by cavis** [comment]
Local testing:

- [ ] Fixer
- [ ] networks
- [ ] castle
- [x] remix-select - worked!  changed:
    ```
    SSO_BASE_URL = "https://proxy.prx.org/sso/user/"
    OmniAuth::Strategies::PRX.default_options['client_options']['site'] = 'https://proxy.prx.org'
    PRX::Client.host    = "proxy.prx.org"
    PRX::Client.port    = 443
    ```
- [ ] wfmt-services

**Comment by cavis** [comment]
@kookster so it sounds like fixer, networks and castle should just be updated to point directly at exchange.prx.org.  And we can do that ahead of time.  We may have to revisit/retest them against an ALB before moving Exchange onto ECS.  (Or have them do non-SSL oauth... ugh).

Remix-select is fine, even using http/80 instead of https/443.  (It just follows the redirect).  And wfmt-services is fine.

**Comment by cavis** [comment]
Seems like @kookster has updated those 3 apps.  So we're good!
